### ISSUE TITLE
Error, nz in the firegrid is not the same of fastfuel

### ISSUE THREAD

**Issue by zacharycope0** [QF-Error-Tracking/QFVD5#24]
**Run Set-up Error:**
David, I got this error when trying to run an old simulation with QF-531:
![image](https://github.com/QF-Error-Tracking/QFVD5/assets/43671145/41091b6e-589d-4dbf-a045-e7ebc14f1d23)

**Question:**
What is the best practice when my FF .dat files have an nz of 128, but there is only fuel in the first 40m? Should we alter the .dat files and remove nz rows above the canopy? Will that improve speed?

**Comment by drobinson6045** [comment]
Yes you would have to alter the .dat if you wanted to be more efficient.  All those extra empty cells still have winds interpolated to them so that's a waste of cpu resources.  

I've started some work to get around this situation where the code would automatically redefine the fire grid to lose unneeded fuel cells. Although this would add complications like reading/drawing output using .inps and such.  As of now trimming down the .dats is the only way.

**Comment by zacharycope0** [comment]
Ok thanks.
